### ISSUE TITLE
A way to exclude code regions from profiling?

### ISSUE THREAD

**Issue by wohlbier** [benroywillis/TraceAtlas#11]
Hi, is there a way to exclude regions of the code from being included in the profile?

**Comment by benroywillis** [comment]
There is currently no functionality to do this. I believe this was a feature that the last grad student, Richard Uhrie, built for you. Is that true?

**Comment by wohlbier** [comment]
Indeed he did. I thought I might need it to get through my current issues, but it appears that I don't. Closing for now.
