### ISSUE TITLE
release or dev?

### ISSUE THREAD

**Issue by wohlbier** [benroywillis/TraceAtlas#9]
Hi, which branch should we be using for evaluation. I'm running into a numerical exception and wondering if I should pull from your dev branch.

```
(base) [jgwohlbier@etc-gpu-09 build]$ ctest --rerun-failed --output-on-failure
Test project /srv/data_local/jgwohlbier/DSSoC/DASH/spmm/build
    Start 1: spmm_trace
1/1 Test #1: spmm_trace .......................***Exception: Numerical  0.38 sec


0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.39 sec

The following tests FAILED:
	  1 - spmm_trace (NUMERICAL)
Errors while running CTest
```

**Comment by benroywillis** [comment]
I haven't seen this error yet in any of my tests for v1.0.0. I also haven't gotten this exception for any tests of the current pull request that should be done before the end of this week (v1.1.0). 

Are you just profiling in this case? Or are there other tools included in this test?

**Comment by wohlbier** [comment]
Yes, that was profiling. It was resolved by switching to the dev branch. I didn't look at the diffs between the dev branch vs the 1.0.0 at the time, but whatever they were they fixed the issue.
